### ISSUE TITLE
Sredi da se poruke salju kroz mrezu

### ISSUE THREAD

**Issue by lazer-nikolic** [LudiMajkan/NIKPES#1]
Ja ne mogu da verujem da ovo još uvek nije implementirano. Od 25. oktobra, otkad je ovaj nesrećni repozitorijum začet, na ovom feature-u nije rađeno NISTA. Ja odbijam da plaćam sve silne novce koje sam marljivo skupljao tokom godina rada u hladnim, mračnim i vlažnim sibirskim rudnicima soli. Na nuspojavama Bensedina se nalazi adresa ovog repozitorijuma. Kada se ovaj kod potera na serveru iz groba Marije Magdalene se čuju bolni krici. Svetska zdravstvena organizacija rangira ovaj kod kao glavni uzrok smrti dece jedno mesto ispod gladi i afričkih odreda smrti. Saberi se, Nenade.

**Comment by NenadDragisic** [comment]
Rešeno bugi, nego me mrzi da editujem to. Btw hteo sam da ti editujem post nekim gej forama, ali mi te žao, ne mora ceo svet da sazana ako ti nisi spreman. :P
